<div class="container">

    <div class="col-md-12 text-center">

        <br />
        <br />

        <img src="<?php echo $this->config->website; ?>content/phalcon-php.png" />

        <br />
        <h1>Destruti Phalcon Basic</h1>
        <h2>Server Examlple Architecture in Phalcon</h2>

        <br />
        <br />

        <h4>
            <a href="https://github.com/destruti/php-phalcon-basic-structure">
                Src at https://github.com/destruti/php-phalcon-basic-structure
            </a>
        </h4>

        <br />
        <br />
        <br />

        <form action="/getTransfer" method="post">
            <button type="submit" class="btn btn-default SecureKey">Get Transfer</button>
        </form>

    </div>

</div>